project_id = "gkaaqbqzgdulzspdhupe"

[functions.admin-check-password]
verify_jwt = false

[functions.admin-manage-book]
verify_jwt = false

[functions.admin-manage-copy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-loan-approval-email]
verify_jwt = false

[functions.send-loan-rejection-email]
verify_jwt = false

[functions.admin-manage-loan]
verify_jwt = false

[functions.daily-overdue-check]
verify_jwt = false

[functions.process-borrow-request]
verify_jwt = false

[functions.bulk-import-books]
verify_jwt = false